apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Kolkata
            - name: FTLCONF_dns_listeningMode
              value: all
            - name: FTLCONF_dns_upstreams
              value: 1.1.1.1;8.8.8.8
            - name: FTLCONF_misc_dnsmasq_lines
              value: "address=/sample.lan/10.0.0.46"
          volumeMounts:
            - name: config
              mountPath: /etc/pihole
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pihole-config
