apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pihole-config-local
  hostPath:
    path: /mnt/2000CRU2/pihole
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-config-local
  resources:
    requests:
      storage: 20Gi
  volumeName: pihole-config
