apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.4.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/kubernetes/networking/traefik/values.yaml

    - repoURL: git@github.com:mandeepmails/homelab-infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
