deployment:
  kind: DaemonSet

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.0.0.46

ingressClass:
  enabled: true
  name: traefik
  isDefaultClass: false

gateway:
  enabled: true

gatewayClass:
  enabled: true

providers:
  kubernetesCRD:
    enabled: true

  kubernetesGateway:
    enabled: true

  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
    matchRule: Host(`dashboard.localhost`)

extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: IngressClass
    metadata:
      name: public
      annotations:
        ingressclass.kubernetes.io/is-default-class: "true"
    spec:
      controller: traefik.io/ingress-controller
