apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:mandeepmails/homelab-infra.git
        revision: main
        directories:
          - path: kubernetes/apps/*
          - path: kubernetes/apps/argocd
            exclude: true

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: git@github.com:mandeepmails/homelab-infra.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
